<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- RemoveAllResilienceHandlers ainda é marcado como experimental -->
    <NoWarn>$(NoWarn);EXTEXP0001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.5.4" />
    <PackageReference Include="Aspire.StackExchange.Redis.DistributedCaching" Version="13.5.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Loja.ServiceDefaults\Loja.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
